name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - ryanshaut
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature would be used.
      render: python
    validations:
      required: false
  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - label: New authentication flow
        - label: Admin API enhancement
        - label: New client method
        - label: Documentation improvement
        - label: Example/tutorial
        - label: Performance improvement
        - label: Developer experience improvement
        - label: Other
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false